# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.4
    - 2.7
    - 3.3
env:
    - GROUP=js
    - GROUP=
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - time sudo add-apt-repository -y ppa:pcarrier/ppa
    - time sudo apt-get update
    - time sudo apt-get install pandoc casperjs nodejs libzmq3-dev
    - time pip install -f https://nipy.bic.berkeley.edu/wheelhouse/travis jinja2 sphinx pygments tornado requests mock pyzmq jsonschema jsonpointer
install:
    - time python setup.py install -q 
script:
    - cd /tmp && iptest $GROUP

matrix:
    exclude:
        - python: 3.3
          env: GROUP=js
