# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.4
    # - 2.7
    # - 3.3
env:
  global:
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0
  matrix:
    - GROUP=js/services
    - GROUP=js/notebook
    # - GROUP=js/base
    # - GROUP=js/tree
    # - GROUP=js/widgets
    # - GROUP=
addons:
    firefox: "32.0"
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # slimerjs
    - '[[ $GROUP == js* ]] && wget https://9c3695669ccd6962f554-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/phantomjs.zip'
    - '[[ $GROUP == js* ]] && unzip phantomjs.zip'
    - '[[ $GROUP == js* ]] && export "PATH=$PWD/phantomjs:$PATH"'
    # casperjs
    - '[[ $GROUP == js* ]] && wget https://github.com/minrk/casperjs/archive/phantom-2-fix.tar.gz -O /tmp/casper.tar.gz'
    - '[[ $GROUP == js* ]] && tar -xvf /tmp/casper.tar.gz'
    - '[[ $GROUP == js* ]] && export PATH="$PWD/casperjs-phantom-2-fix/bin:$PATH"'
    # pandoc
    - wget https://9c3695669ccd6962f554-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/pandoc-1.12.3-linux-debian-x86_64.zip -O /tmp/pandoc.zip
    - unzip /tmp/pandoc.zip
    - 'export PATH="$PWD/pandoc:$PATH"'
    # get python wheels
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    # use local mathjax
    - '[[ $GROUP == js* ]] && python -m IPython.external.mathjax'
install:
    - 'time pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipython[all]'
script:
    - cd /tmp && iptest $GROUP

matrix:
    exclude:
        - python: 3.3
          env: GROUP=js
