# http://travis-ci.org/#!/ipython/ipython
language: python
sudo: false
cache:
    pip: true
    directories:
        - .ipython/nbextensions
        - casperjs
        - pandoc
python:
    - 3.4
    - 2.7
    - 3.3
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$TRAVIS_BUILD_DIR/casperjs/bin:$TRAVIS_BUILD_DIR/phantomjs:$PATH
    - IPYTHONDIR=$TRAVIS_BUILD_DIR/.ipython
  matrix:
    - GROUP=js/base
    - GROUP=js/notebook
    - GROUP=js/tree
    - GROUP=js/widgets
    - GROUP=
before_install:
    # # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    # - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - 'if [[ $GROUP == js* && ! -e casperjs/bin ]]; then wget https://7de4dfdec62155b49b44-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/casperjs.zip && unzip dl/casperjs.zip; fi'
    - 'if [[ $GROUP != js* && ! -e pandoc/pandoc ]]; then wget https://7de4dfdec62155b49b44-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/pandoc-1.12.3-linux-debian-x86_64.zip && unzip dl/pandoc-1.12.3-linux-debian-x86_64.zip; fi'
    - env
    - 'if [[ $GROUP == js* ]]; then python -m IPython.external.mathjax; fi'
install:
    - pip install file://$PWD#egg=ipython[all] coveralls
script:
    - cd /tmp && iptest $GROUP --coverage xml && cd -

matrix:
    exclude:
        - python: 3.3
          env: GROUP=js/base
        - python: 3.3
          env: GROUP=js/notebook
        - python: 3.3
          env: GROUP=js/tree
        - python: 3.3
          env: GROUP=js/widgets

after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - coveralls
