# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.4
    # - 2.7
    # - 3.3
env:
  global:
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0
  matrix:
    - GROUP=js/services
    - GROUP=js/notebook
    # - GROUP=js/base
    # - GROUP=js/tree
    # - GROUP=js/widgets
    # - GROUP=
addons:
    firefox: "32.0"
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # slimerjs
    - '[[ $GROUP == js* ]] && sh -e /etc/init.d/xvfb start'
    - '[[ $GROUP == js* ]] && wget http://download.slimerjs.org/v0.9/0.9.3/slimerjs-0.9.3.zip'
    - '[[ $GROUP == js* ]] && unzip slimerjs-0.9.3.zip'
    - '[[ $GROUP == js* ]] && mv slimerjs-0.9.3 ./slimerjs'
    - '[[ $GROUP == js* ]] && export "PATH=$PWD/slimerjs:$PATH"'
    # casperjs
    - '[[ $GROUP == js* ]] && wget https://github.com/n1k0/casperjs/archive/1.1-beta3.tar.gz -O /tmp/casper.tar.gz'
    - '[[ $GROUP == js* ]] && tar -xvf /tmp/casper.tar.gz'
    - '[[ $GROUP == js* ]] && export PATH="$PWD/casperjs-1.1-beta3/bin:$PATH"'
    # pandoc
    - wget https://9c3695669ccd6962f554-d726a73613a1989d29b147f20996e7c1.ssl.cf2.rackcdn.com/pandoc-1.12.3-linux-debian-x86_64.zip -O /tmp/pandoc.zip
    - unzip /tmp/pandoc.zip
    - 'export PATH="$PWD/pandoc:$PATH"'
    # get python wheels
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    # use local mathjax
    - '[[ $GROUP == js* ]] && python -m IPython.external.mathjax'
    - '[[ $GROUP == js* ]] && export ARGS="--slimerjs"'
install:
    - 'time pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipython[all]'
script:
    - cd /tmp && iptest $GROUP $ARGS

matrix:
    exclude:
        - python: 3.3
          env: GROUP=js
